<?php

/**
 * @file
 * Thunder riddle install hooks.
 */

/**
 * Implements hook_menu_local_actions_alter().
 */
function thunder_riddle_menu_local_actions_alter(&$local_actions) {
  /** @var \Drupal\config_selector\ActiveEntity $config_selector */
  $config_selector = \Drupal::service('config_selector.active');
  /** @var \Drupal\views\ViewEntityInterface $view */
  $view = $config_selector->get('view', 'thunder_media_view');
  if ($view && $view->status()) {
    $view->getExecutable()->initDisplay();
    $local_actions['riddle_marketplace.import']['appears_on'][] = $view->getExecutable()->getUrl()->getRouteName();
  }
}

/**
 * Implements template_preprocess_views_view().
 */
function thunder_riddle_preprocess_views_view(&$variables) {

  if ($variables['view']->id() == 'riddle_browser') {
    $variables['view_array']['#attached']['library'][] = 'thunder_riddle/entity_browser_view';
  }
}
