thunder_media.settings:
  type: config_object
  mapping:
    enable_filename_transliteration:
      type: boolean
      label: 'Default transliteration'
    enable_filefield_remove_button:
      type: boolean
      label: 'Default transliteration'
