#!/bin/bash
#
# Script that will build Thunder and set all required configurations

# Get Branch info
BRANCH_NAME=${BRANCH_NAME:-'8.x-2.x'}

# Install branch of thunder distribution
composer create-project burdamagazinorg/thunder-project:2.x ~/www --no-interaction --stability dev --no-install
cd ~/www
composer require burdamagazinorg/thunder:dev-${BRANCH_NAME} thunder/thunder_performance_measurement:dev-master

# Set other requirements
mkdir -p ~/www/config/sync

### Prepare NightwatchJS requirements ###

# Install Elastic APM
cd /home/thunder/www/docroot/core
yarn add elastic-apm-node --dev
