<?php

/**
 * @file
 * Hook implementations.
 */

use Drupal\field\Entity\FieldConfig;

/**
 * Implements hook_modules_installed().
 */
function thunder_liveblog_modules_installed($modules) {
  // Remove liveblog form display. We provide our own.
  if (in_array('liveblog', $modules)) {
    if ($field = FieldConfig::load('node.liveblog.body')) {
      $field->delete();
      field_purge_batch(10);
    }
    $configs = [
      'core.entity_form_display.node.liveblog.default',
      'core.entity_form_display.liveblog_post.liveblog_post.default',
      'core.entity_view_display.liveblog_post.liveblog_post.default',
      'core.entity_view_display.node.liveblog.default',
    ];
    $configFactory = \Drupal::configFactory();
    foreach ($configs as $config) {
      $configFactory->getEditable($config)->delete();
    }
    \Drupal::service('config.installer')->installOptionalConfig();
  }
}
