<?php
/**
 * @file
 * Contains
 */

/**
 * Implements hook_ENTITY_TYPE_create().
 */
function thunder_media_file_create(\Drupal\file\Entity\File $entity) {

  $config = \Drupal::config('thunder_media.settings');

  if ($config->get('enable_filename_transliteration')) {

    $pathinfo = pathinfo($entity->getFilename());

    /** @var \Drupal\pathauto\AliasCleaner $aliasCleaner */
    $aliasCleaner = \Drupal::service('pathauto.alias_cleaner');

    $cleanFilename = $aliasCleaner->cleanString($pathinfo['filename']) . '.' . $pathinfo['extension'];

    $entity->setFilename($cleanFilename);
  }
}

/**
 * Implements hook_preprocess_views_view().
 */
function thunder_media_preprocess_views_view(&$variables) {
  if ($variables['view']->id() === 'image_browser') {
    $variables['view_array']['#attached']['library'][] = 'media_entity_browser/view';
  }
}
