<?php

/**
 * @file
 * Contains Thunder taxonomy access install / uninstall hooks.
 */

/**
 * Implements hook_install().
 */
function thunder_taxonomy_access_install() {
  // Add our base fields to the schema.
  \Drupal::service('entity.definition_update_manager')->applyUpdates();

}

/**
 * Implements hook_uninstall().
 */
function thunder_taxonomy_access_uninstall() {
  // Remove our base fields from the schema.
  \Drupal::service('entity.definition_update_manager')->applyUpdates();
}
