<?php

namespace Drupal\Tests\thunder\FunctionalJavascript;

/**
 * Tests the article creation.
 *
 * @group thunder
 */
class ArticleCreationTest extends ThunderJavascriptTestBase {

  protected function setUp() {

    parent::setUp(); // TODO: Change the autogenerated stub

    $admin_user = $this->drupalCreateUser([
      'view the administration theme',
      'access content',
      'access content overview',
      'create article content',
      'administer nodes',
      'access image_browser entity browser pages',
      'access media_browser entity browser pages',
      'access multiple_image_browser entity browser pages',
    ]);
    $this->drupalLogin($admin_user);
  }

  public function testCreateArticle() {

    $this->drupalGet('node/add/article');

    $page = $this->getSession()->getPage();

    $page->selectFieldOption('field_channel', 1);

    $this->createScreenshot('foo.jpg');

    $page->fillField('title[0][value]', 'Test article');
    $page->fillField('field_seo_title[0][value]', 'Massive gaining seo traffic text');

    $page->pressButton('Save and publish');

    $this->assertSession()->titleEquals('Massive gaining seo traffic text');

    $this->assertSession()->pageTextContains('Test article');
  }
}
