thunder_article.settings:
  type: config_object
  mapping:
    move_scheduler_local_task:
      type: boolean
      label: 'Move scheduler to local task of content list'
    thunder_article_metatags:
      type: mapping
      label: "Move metatag tags into the 'Thunder' group"
