<?php

/**
 * @file
 * Contains hook integrations.
 */

use Drupal\search_api\Plugin\views\query\SearchApiQuery;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_data().
 */
function thunder_search_views_data() {
  $data['views']['facet_block'] = [
    'title' => t('Facet block'),
    'help' => t('.'),
    'area' => [
      'id' => 'facet_block',
    ],
  ];
  return $data;
}

/**
 * Implements hook_views_pre_render().
 */
function thunder_search_views_pre_render(ViewExecutable $view) {
  if ($view->result || !$view->query instanceof SearchApiQuery) {
    return;
  }

  /** @var \Drupal\search_api\Task\IndexTaskManagerInterface $index_task_manager */
  $index_task_manager = \Drupal::service('search_api.index_task_manager');

  $index = $view->query->getIndex();
  if (!$index_task_manager->isTrackingComplete($index) || $index->getTrackerInstance()->getRemainingItemsCount()) {
    \Drupal::messenger()->addError(t("It's needed to <a href='/admin/config/search/search-api/index/content'>index the search index</a> in order to have all content searchable."));
  }

}
