<?php

/**
 * @file
 * Contains hook integrations.
 */

/**
 * Implements hook_views_data().
 */
function thunder_search_views_data() {
  $data['views']['facet_block'] = [
    'title' => t('Facet block'),
    'help' => t('.'),
    'area' => [
      'id' => 'facet_block',
    ],
  ];
  return $data;
}

/**
 * Implements hook_menu_local_actions_alter().
 */
function thunder_search_menu_local_actions_alter(&$local_actions) {
  /** @var \Drupal\views\ViewEntityInterface $view */
  $view = \Drupal::entityTypeManager()->getStorage('view')->load('media_search');
  if ($view && $view->status()) {
    $local_actions['media.add']['appears_on'][] = 'view.media_search.page_1';
  }
}

/**
 * Implements hook_menu_links_discovered_alter().
 */
function thunder_search_menu_links_discovered_alter(&$links) {
  /** @var \Drupal\views\ViewEntityInterface $view */
  $view = \Drupal::entityTypeManager()->getStorage('view')->load('media_search');
  if ($view && $view->status()) {
    $links['entity.media.collection']['route_name'] = 'view.media_search.page_1';
  }
}
