field.field.node.article.field_paragraphs:
  expected_config: {  }
  update_actions:
    add:
      settings:
        handler_settings:
          target_bundles:
            pinterest: pinterest
          target_bundles_drag_drop:
            pinterest:
              enabled: true
              weight: 9
