content_lock.settings:
  expected_config:
    form_op_lock:
      thunder_updater_update:
        mode: null
        values: {  }
    types:
      thunder_updater_update: {  }
  update_actions:
    change:
      form_op_lock:
        update_helper_checklist_update:
          mode: null
          values: {  }
      types:
        update_helper_checklist_update: {  }
    delete:
      form_op_lock:
        thunder_updater_update:
          mode: null
          values: {  }
      types:
        thunder_updater_update: {  }
