core.entity_form_display.media.image.default:
  expected_config:
    third_party_settings:
      field_group:
        group_credits:
  update_actions:
    change:
      third_party_settings:
        field_group:
          group_credits:
            region: content
core.entity_form_display.media.video.default:
  expected_config:
    third_party_settings:
      field_group:
        group_credits:
  update_actions:
    change:
      third_party_settings:
        field_group:
          group_credits:
            region: content
