core.entity_form_display.media.instagram.default:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        field_author: true
        field_content: true
core.entity_form_display.media.twitter.default:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        field_author: true
        field_content: true
core.entity_view_display.media.instagram.default:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        field_author: true
        field_content: true
core.entity_view_display.media.instagram.thumbnail:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        field_author: true
        field_content: true
core.entity_view_display.media.twitter.default:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        field_author: true
        field_content: true
media_entity.bundle.twitter:
  expected_config:
    field_map: {  }
  update_actions:
    change:
      field_map:
        content: field_content
        user: field_author
    add:
      third_party_settings:
        crop:
          image_field: null
        media_expire:
          enable_expiring: null
          expire_field: null
          fallback_media: null
core.entity_form_display.paragraph.image.default:
  expected_config:
    content:
      field_image:
        settings:
          field_widget_display: rendered_entity
          field_widget_edit: true
  update_actions:
    change:
      content:
        field_image:
          settings:
            field_widget_display: inline_entity_form
            field_widget_display_settings:
              form_mode: inline
            field_widget_edit: false
    remove:
      content:
        field_image:
          settings:
            field_widget_display_settings:
              view_mode: thumbnail
core.entity_form_display.paragraph.video.default:
  expected_config:
    content:
      field_video:
        settings:
          field_widget_display: rendered_entity
          field_widget_edit: true
  update_actions:
    change:
      content:
        field_video:
          settings:
            field_widget_display: inline_entity_form
            field_widget_display_settings:
              form_mode: inline
            field_widget_edit: false
    remove:
      content:
        field_video:
          settings:
            field_widget_display_settings:
              view_mode: thumbnail
core.entity_view_display.paragraph.gallery.preview:
  expected_config:
    content:
      field_media:
        settings:
          image_link: ''
          image_style: media_thumbnail
        type: media_thumbnail
  update_actions:
    remove:
      content:
        field_media:
          settings:
            image_link: false
            image_style: media_thumbnail
    change:
      content:
        field_media:
          settings:
            link: false
            view_mode: paragraph_preview
          type: entity_reference_entity_view
core.entity_view_display.paragraph.image.preview:
  expected_config:
    content:
      field_image:
        settings:
          view_mode: thumbnail
  update_actions:
    change:
      content:
        field_image:
          settings:
            view_mode: paragraph_preview
core.entity_view_display.paragraph.instagram.preview:
  expected_config:
    content:
      field_media:
        settings:
          view_mode: thumbnail
  update_actions:
    change:
      content:
        field_media:
          settings:
            view_mode: paragraph_preview
core.entity_view_display.paragraph.video.preview:
  expected_config:
    content:
      field_video:
        settings:
          view_mode: thumbnail
  update_actions:
    change:
      content:
        field_video:
          settings:
            view_mode: paragraph_preview
core.entity_form_display.node.article.default:
  expected_config:
    third_party_settings:
      field_group:
        group_basis:
          format_settings:
            classes: ''
        group_paragraphs:
          format_settings:
            classes: paragraphs-container
        group_teaser:
          format_settings:
            classes: article-teaser
  update_actions:
    change:
      third_party_settings:
        field_group:
          group_basis:
            format_settings:
              classes: content-form__form-section
          group_paragraphs:
            format_settings:
              classes: 'content-form__form-section paragraphs-container'
              description: ''
          group_teaser:
            format_settings:
              classes: 'content-form__form-section article-teaser'
    add:
      third_party_settings:
        field_group:
          group_basis:
            format_settings:
              label: Basis
block.block.thunder_admin_breadcrumbs:
  expected_config:
    region: breadcrumb
    weight: 0
  update_actions:
    change:
      region: header
      weight: -2
block.block.thunder_admin_page_title:
  expected_config:
    weight: -30
  update_actions:
    change:
      weight: -3
block.block.thunder_admin_primary_local_tasks:
  expected_config:
    weight: 0
  update_actions:
    change:
      weight: -1
