core.entity_form_display.node.article.default:
  expected_config:
    content:
      field_channel:
        settings: {  }
        type: options_select
      field_tags:
        settings:
          match_operator: CONTAINS
          placeholder: ''
          size: 60
        type: entity_reference_autocomplete_tags
  update_actions:
    change:
      content:
        field_channel:
          settings:
            autocomplete: false
          type: select2_entity_reference
        field_tags:
          settings:
            autocomplete: true
          type: select2_entity_reference
    delete:
      content:
        field_tags:
          settings:
            match_operator: CONTAINS
            placeholder: ''
            size: 60
