filter.format.full_html:
  expected_config:
    weight: 1
  update_actions:
    change:
      weight: 2
filter.format.restricted_html:
  expected_config:
    weight: 0
  update_actions:
    change:
      weight: 1
