core.entity_form_display.node.article.default:
  expected_config:
    content:
      field_channel:
        type: options_select
        settings: {  }
      field_tags:
        settings:
          match_operator: CONTAINS
          placeholder: ''
          size: 60
        third_party_settings: {  }
        type: entity_reference_autocomplete_tags
  update_actions:
    change:
      content:
        field_channel:
          type: select2_autocomplete_widget
          settings:
            autocomplete: false
        field_tags:
          type: select2_autocomplete_widget
          settings:
            autocomplete: true
