core.entity_form_display.node.page.default:
  expected_config:
    content:
      uid:
        settings:
          placeholder: ''
          size: 60
        type: entity_reference_autocomplete
  update_actions:
    add:
      content:
        uid:
          settings:
            autocomplete: true
    change:
      content:
        uid:
          settings:
            width: 100%
          type: select2_entity_reference
    delete:
      content:
        uid:
          settings:
            placeholder: ''
            size: 60
core.entity_form_display.media.gallery.default:
  expected_config:
    content:
      uid:
        settings:
          placeholder: ''
          size: 60
        type: entity_reference_autocomplete
  update_actions:
    add:
      content:
        uid:
          settings:
            autocomplete: true
    change:
      content:
        uid:
          settings:
            width: 100%
          type: select2_entity_reference
    delete:
      content:
        uid:
          settings:
            placeholder: ''
            size: 60
core.entity_form_display.media.image.default:
  expected_config:
    content:
      uid:
        settings:
          placeholder: ''
          size: 60
        type: entity_reference_autocomplete
  update_actions:
    add:
      content:
        uid:
          settings:
            autocomplete: true
    change:
      content:
        uid:
          settings:
            width: 100%
          type: select2_entity_reference
    delete:
      content:
        uid:
          settings:
            placeholder: ''
            size: 60
core.entity_form_display.media.instagram.default:
  expected_config:
    content:
      uid:
        settings:
          placeholder: ''
          size: 60
        type: entity_reference_autocomplete
  update_actions:
    add:
      content:
        uid:
          settings:
            autocomplete: true
    change:
      content:
        uid:
          settings:
            width: 100%
          type: select2_entity_reference
    delete:
      content:
        uid:
          settings:
            placeholder: ''
            size: 60
core.entity_form_display.media.pinterest.default:
  expected_config:
    content:
      uid:
        settings:
          placeholder: ''
          size: 60
        type: entity_reference_autocomplete
  update_actions:
    add:
      content:
        uid:
          settings:
            autocomplete: true
    change:
      content:
        uid:
          settings:
            width: 100%
          type: select2_entity_reference
    delete:
      content:
        uid:
          settings:
            placeholder: ''
            size: 60
core.entity_form_display.media.twitter.default:
  expected_config:
    content:
      uid:
        settings:
          placeholder: ''
          size: 60
        type: entity_reference_autocomplete
  update_actions:
    add:
      content:
        uid:
          settings:
            autocomplete: true
    change:
      content:
        uid:
          settings:
            width: 100%
          type: select2_entity_reference
    delete:
      content:
        uid:
          settings:
            placeholder: ''
            size: 60
core.entity_form_display.media.video.default:
  expected_config:
    content:
      uid:
        settings:
          placeholder: ''
          size: 60
        type: entity_reference_autocomplete
  update_actions:
    add:
      content:
        uid:
          settings:
            autocomplete: true
    change:
      content:
        uid:
          settings:
            width: 100%
          type: select2_entity_reference
    delete:
      content:
        uid:
          settings:
            placeholder: ''
            size: 60
core.entity_form_display.node.article.default:
  expected_config:
    content:
      uid:
        settings:
          placeholder: ''
          size: 60
        type: entity_reference_autocomplete
  update_actions:
    add:
      content:
        field_paragraphs:
          settings:
            closed_mode_threshold: 0
        field_tags:
          settings:
            match_operator: CONTAINS
            width: 100%
        field_teaser_media:
          settings:
            field_widget_replace: false
        uid:
          settings:
            autocomplete: true
    change:
      content:
        uid:
          settings:
            width: 100%
          type: select2_entity_reference
    delete:
      content:
        uid:
          settings:
            placeholder: ''
            size: 60
