editor.editor.basic_html:
  expected_config: {  }
  update_actions:
    add:
      settings:
        toolbar:
          rows:
            -1:
              -1:
                items:
                  - SplitTextAfter
            0:
              -1:
                items:
                  - SplitTextBefore
