core.entity_form_display.paragraph.media.default:
  expected_config:
    content:
      field_media:
        settings:
          field_widget_display: 'rendered_entity'
  update_actions:
    change:
      content:
        field_media:
          settings:
            field_widget_display: 'inline_entity_form'
            field_widget_edit: false
            field_widget_display_settings:
              form_mode: 'inline'
