__global_actions:
  install_modules:
    - media_entity_pinterest
  import_configs:
    - paragraphs.paragraphs_type.pinterest
    - field.field.paragraph.pinterest.field_media
    - core.entity_view_display.paragraph.pinterest.default
    - core.entity_view_display.paragraph.pinterest.preview
    - core.entity_form_display.paragraph.pinterest.default
field.field.node.article.field_paragraphs:
  expected_config: {  }
  update_actions:
    add:
      settings:
        handler_settings:
          target_bundles:
            pinterest: pinterest
          target_bundles_drag_drop:
            pinterest:
              enabled: true
              weight: 9
