__global:
 install_modules:
  - shariff
core.entity_view_display.node.article.default:
 expected_config: {  }
 update_actions:
  add:
   content:
    shariff_field:
     weight: 3
     settings: {  }
     third_party_settings: {  }
     region: content
