field.field.node.article.field_paragraphs:
  expected_config:
    label: 'Paragraphs (Good luck!)'
    settings:
      handler_settings:
        negate: 1
        target_bundles: null
        target_bundles_drag_drop:
          gallery:
            enabled: false
          image:
            enabled: false
          instagram:
            enabled: false
          link:
            enabled: false
          pinterest:
            enabled: false
          quote:
            enabled: false
          text:
            enabled: false
          twitter:
            enabled: false
          video:
            enabled: false
  update_actions:
    change:
      label: Paragraphs
      settings:
        handler_settings:
          target_bundles:
            gallery: gallery
            image: image
            instagram: instagram
            link: link
            pinterest: pinterest
            quote: quote
            text: text
            twitter: twitter
            video: video
          target_bundles_drag_drop:
            gallery:
              enabled: true
            image:
              enabled: true
            instagram:
              enabled: true
            link:
              enabled: true
            pinterest:
              enabled: true
            quote:
              enabled: true
            text:
              enabled: true
            twitter:
              enabled: true
            video:
              enabled: true
    delete:
      settings:
        handler_settings:
          negate: 1
