<?php

/**
 * @file
 * Thunder Article module hooks.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_node_article_edit_form_alter().
 */
function thunder_article_form_node_article_edit_form_alter(&$form, FormStateInterface $form_state) {
  _thunder_article_form_alter_helper($form, $form_state);
}

/**
 * Implements hook_form_node_article_form_alter().
 */
function thunder_article_form_node_article_form_alter(&$form, FormStateInterface $form_state) {
  _thunder_article_form_alter_helper($form, $form_state);
}

/**
 * Helper function for article form alter hooks.
 */
function _thunder_article_form_alter_helper(&$form, FormStateInterface $form_state) {
  // Add CSS file for layout optimization.
  $form['#attached']['library'][] = 'thunder_article/article_form_styling';
}

/**
 * Implements hook_theme().
 */
function thunder_article_theme($existing, $type, $render, $path) {
  $theme = array();
  $files = scandir(DRUPAL_ROOT.'/'.$path.'/templates/fb_instant_articles');
  foreach ($files as $file) {
    if($file === '.' || $file === '..') continue;
    $file = str_replace('-', '_', $file);
    $file = basename($file, '.html.twig');
    $base = array();
    preg_match('/([a-z]*)_/', $file, $base);
    $theme[$file] = [
      'path' => $path .'/templates/fb_instant_articles',
      'base hook' => $base[1]
    ];
  }
  return $theme;
}


/**
 * Implements hook_preprocess_views_view_row_fia().
 */
function thunder_article_preprocess_views_view_row_fia(&$variables) {
  $field_teaser_media = $variables['row']['#node']->field_teaser_media;
  /** @var \Drupal\media_entity\Entity\Media $entity */
  $entity = $field_teaser_media->entity;

  $render_controller = \Drupal::entityTypeManager()->getViewBuilder($entity->getEntityTypeId());
  $entityRender = $render_controller->view($entity, 'facebook_instant_articles_rss', NULL);
  $entityHtml = render($entityRender);

  $variables['options']['figure'] = $entityHtml;
}


/**
 * Implements hook_preprocess_paragraph().
 */
function thunder_article_preprocess_paragraph(&$variables) {
  /**
   * @var \Drupal\paragraphs\Entity\Paragraph $paragraph
   */
  $paragraph = $variables['paragraph'];

  if ($variables['view_mode'] == "facebook_instant_articles_rss" && $paragraph instanceof \Drupal\paragraphs\Entity\Paragraph) {
    if($paragraph->getType() == 'media' && $variables['content']['field_media'][0]['#media']->bundle() == 'image') {
      if($paragraph->parent_type->value == 'node') {
        $nid = $paragraph->parent_id->value;
        $node = \Drupal\node\Entity\Node::load($nid);
        $teaser_uri = $node->field_teaser_media->entity->field_image->entity->uri->value;

        $media = $variables['content']['field_media'][0]['#media'];
        $media_uri = $media->field_image->entity->uri->value;

        if($teaser_uri == $media_uri) {
          $variables = array();
        }
      }
    }
  }
}


